spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzdemo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 9780619
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /res/** #修改静态资源访问路径

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.wzres.domain   # 配置哪个包下的类有默认的别名
