spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 9780619
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.153.48 #redis服务器ip地址
    port: 6379  #redis端口号

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # mapper映射文件路径
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
